---
- name: Windows update
  hosts: all
  gather_facts: false
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates']
      register: result
    - debug: var=result
    - win_reboot:
      when: result.reboot_required
      