---
- name: Uninstall Podman etc.
  yum:
    name: ['buildah', 'skopeo', 'podman', 'containers-common', 'atomic-registries', 'docker']
    state: absent

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Figure out latest Docker Compose file from latest tag
  get_url:
    url: "https://api.github.com/repos/docker/compose/releases/latest"
    force: yes
    headers:
      Accept: "application/vnd.github.v3+json"
    dest: "/tmp/docker-compose.json"

- name: Get download url 
  shell: |
    cat "/tmp/docker-compose.json" | jq '.assets | .[] | select(.browser_download_url | contains("docker-compose-Linux-x86_64\"")) | .url' | sed -e 's/^"//' -e 's/"$//'
  register: "download_url"

- debug:
    msg: "{{ download_url.stdout }}"

- name: Download latest release
  get_url:
    url: "{{ download_url.stdout }}"
    dest: /usr/local/bin/docker-compose
    tmp_dest: /tmp/
    force: yes
    headers:
      Accept: "application/octet-stream"