---
- name: Uninstall Podman etc.
  yum:
    name: ['buildah', 'skopeo', 'podman', 'containers-common', 'atomic-registries', 'docker']
    state: absent

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Install pip3
  package:
    name: python3-pip
    state: latest 

- name: Pip install docker-compose
  pip:
    name: docker-compose

- name: Set firewall to masquerade
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true
    zone: dmz

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Add user to docker group
  user:
    name: admin
    groups: docker
    append: yes

- name: Reset ssh connection to reload user permissions
  meta: reset_connection