---
- name: Uninstall Podman etc.
  yum:
    name: ['buildah', 'skopeo', 'podman', 'containers-common', 'atomic-registries', 'docker']
    state: absent

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Download latest Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    tmp_dest: /tmp/
    force: yes
    headers:
      Accept: "application/octet-stream"
    mode: a+x

- name: Create symlink for docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: Configure firewall
  firewalld:
    zone: trusted
    interface: docker0
    permanent: true
    state: enabled

- name: Set firewall to masquerade
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true
    zone: dmz

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded