---
- hosts: all
  become: yes
  vars:
    nfsmounts:
      - {  path: "/mnt/nfs_mount_1", src: "//fs01/nfsshare1" }
      - {  path: "/mnt/nfs_mount_2", src: "//fs01/nfsshare2" }
  tasks:
      - name: mount the nfsshare in client side
        mount:
          fstype: nfs
          opts: defaults
          dump: 0
          passno: 0
          state: mounted
          src: "{{item.src}}"
          path: "{{item.path}}"
        with_items: "{{nfsmounts}}"