---
- hosts: all
  become: yes
  vars:
    nfsmounts:
      - {  path: "/mnt/nfs_mount_1", src: "fs01:/nfsshare1" }
      - {  path: "/mnt/nfs_mount_2", src: "fs01:/nfsshare2" }
  tasks:
      - name: mount the nfsshare in client side
        mount:
          fstype: nfs
          opts: defaults
          dump: 0
          passno: 0
          state: mounted
          src: "{{item.src}}"
          path: "{{item.path}}"
        with_items: "{{nfsmounts}}"

      - name: "mount share"
        mount:
          state: "mounted"
          fstype: "cifs"
          name: /mnt/win/
          src: "//192.168.1.86/instshare"
          opts: "credentials=/root/.smb_passwords,file_mode=0644,dir_mode=0755,gid=root,uid=root"