---
- hosts: all
  become: true
  roles:
    - role: centos_repo
      ssl_crt:
        filename: repo.crt
        src: files/repo.crt
      ssl_key:
        filename: repo.key
        src: files/repo.key