---

- hosts: all

  tasks:

  # this task runs 'getenforce' and registers the result into the "sestatus" variable
  # changed_when: false tells ansible never to mark this task as "changed"
  - name: test to see if selinux is running
    command: getenforce
    register: sestatus

  # this task tests to see if the output
  - name: Is SELinux Enabled?
    debug: msg="selinux is enabled {{ sestatus.stdout }}"
    when: '"Enforcing" not in sestatus.stdout'