---
- name: Install nginx
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@nginx"
    - yum-utils
    - epel-release

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Add firewall rules
  command: firewall-cmd --add-service=http --permanent
  notify:
    - restart firewalld

- name: create repo directory
  file:
    path: /data/repos
    state: directory
    owner: nginx
    recurse: yes

- name: copy update-repo daily cron script
  template:
    src: update-repo.j2
    dest: /etc/cron.daily/update-repo
    mode: 755

- name: copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/centos.conf
  notify:
    - restart nginx

- name: permissions for /data/repos
  shell: "semanage fcontext -a -t httpd_sys_content_t '/data/repos(/.*)?'"
  ignore_errors: yes

- name: Restore SELinux Context
  shell: "restorecon -Rv /data/repos"



- name: Set repo hostname
  hostname:
    name: "{{ repo_hostname }}"
