---
- name: Install nginx
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@nginx"
    - yum-utils
    - epel-release

- name: Set up SSL for nginx
  block:

    - name: Create nginx ssl directory
      file:
        path: /etc/nginx/ssl
        state: directory
        owner: nginx
        mode: 700

    - name: Copy crt file
      copy:
        src: "{{ssl_crt.src}}"
        dest: "/etc/nginx/ssl/{{ssl_crt.filename}}"
    
    - name: Copy key file
      copy:
        src: "{{ssl_key.src}}"
        dest: "/etc/nginx/ssl/{{ssl_key.filename}}"

  when: config_ssl|default(false)|bool

- name: copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/centos.conf
  notify:
    - restart nginx

- name: Add firewall rules
  command: firewall-cmd --add-service=http --permanent
  notify:
    - restart firewalld

- name: create repo directory
  file:
    path: "{{repo_location}}"
    state: directory
    owner: nginx
    recurse: yes

- name: copy update-repo daily cron script
  template:
    src: update-repo.j2
    dest: /etc/cron.daily/update-repo
    mode: 755

- name: permissions for the repo location
  shell: "semanage fcontext -a -t httpd_sys_content_t '{{repo_location}}(/.*)?'"
  ignore_errors: yes

- name: Restore SELinux Context
  shell: "restorecon -Rv {{repo_location}}"

- name: Set repo hostname
  hostname:
    name: "{{ repo_hostname }}"
