---
- name: Install nginx
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@nginx"
    - yum-utils
  notify:
    - restart nginx

- name: Add firewall rules
  command: firewall-cmd --add-service=http --permanent
  notify:
    - restart firewalld

- name: create repo directory
  file:
    path: /data/repos
    state: directory

- name: copy update-repo daily cron script
  copy:
    src: files/update-repo
    dest: /etc/cron.daily/update-repo
    mode: 755

- name: copy nginx config
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/conf.d/centos.conf

- name: Set SELinux rules
  tasks:
  - name: permissions for /data/repos
    shell: "semanage fcontext -a -t httpd_sys_content_t '/data/repos(/.*)?'"

  - name: Restore SELinux Context
    shell: "restorecon -Rv /data/repos"

