---
- name: Remove the default public source
  win_chocolatey_source:
    name: chocolatey
    state: absent

- name: Add new internal source
  win_chocolatey_source:
    name: internal_repo
    state: present
    source: "{{choco_repo_location}}"

- name: Disable Chocolatey source
  win_chocolatey_source:
    name: chocolatey
    state: disabled