---
- name: Check if Chocolatey is already installed
  win_shell: (Get-Command choco).Path
  register: get_command_choco

- name: Install Chocolatey
  block: 
    - name: Create C:\temp
      win_file:
        path: C:\temp
        state: directory

    - name: Save InstallChocolatey.ps1 file
      template:
        src: InstallChocolatey.ps1.j2
        dest: c:\temp\InstallChocolatey.ps1

    - name: Run InstallChocolatey.ps1
      win_shell: C:\temp\InstallChocolatey.ps1
      args:
        creates: C:\ProgramData\chocolatey

  ## When choco not installed
  when: not get_command_choco.stderr == ""

- name: Remove the default public source
  win_chocolatey_source:
    name: chocolatey
    state: absent

- name: Add new internal source
  win_chocolatey_source:
    name: internal_repo
    state: present
    source: "{{choco_repo_location}}"

- name: Install default packages
  win_chocolatey:
    name: "{{item}}"
    state: present
  with_items:
    - notepadplusplus
    - git.Install
    - putty.Install
    - 7zip
    - winscp