---
- name: Change the hostname 
  win_hostname:
    name: '{{ dc_hostname }}'
  register: res

- name: Set static IP address
  win_shell: "(new-netipaddress -InterfaceAlias Ethernet0 -IPAddress {{ dc_address }} -prefixlength {{dc_netmask_cidr}} -defaultgateway {{ dc_gateway }})"
  ignore_errors: True 

- name: Reboot
  win_reboot:
  when: res.reboot_required   

- name: Stop the time service
  win_service:
    name: w32time
    state: stopped

- name: Set NTP Servers
  win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ntp_servers}}"'
  
- name: Start the time service
  win_service:
    name: w32time
    state: started

- name: Disable firewall for Domain, Public and Private profiles
  win_firewall:
    state: disabled
    profiles:
    - Domain
    - Private
    - Public
  tags: disable_firewall

- name: install ad
  win_feature: >
      name=AD-Domain-Services
      include_management_tools=yes
      include_sub_features=yes
      state=present
  register: result

- name: Create domain
  win_domain: >
    dns_domain_name='{{ dns_name }}'
    safe_mode_password='{{ safe_mode_password }}'
    create_dns_delegation: no
    database_path: C:\Windows\NTDS
    domain_mode: WinThreshold
    domain_netbios_name: "{{ dns_name.split('.')[0] | lower }}"
    forest_mode: WinThreshold
    sysvol_path: C:\Windows\SYSVOL
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

- name: Create reverse DNS zone
  win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest"   
  retries: 30
  delay: 60
  register: result           
  until: result is succeeded

- name: Check for xRemoteDesktopAdmin Powershell module
  win_psmodule:
    name: xRemoteDesktopAdmin
    state: present

- name: Enable Remote Desktop
  win_dsc:
    resource_name: xRemoteDesktopAdmin
    Ensure: present
    UserAuthentication: NonSecure