---
- name: Change the hostname 
  win_hostname:
    name: '{{ dc_hostname }}'
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required   

- name: install ad
  win_feature: >
      name=AD-Domain-Services
      include_management_tools=yes
      include_sub_features=yes
      state=present
  register: result

- name: install domain
  win_domain: >
    dns_domain_name='{{ dns_name }}'
    safe_mode_password='{{ safe_mode_password }}'
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

- name: Check for xRemoteDesktopAdmin Powershell module
  win_psmodule:
    name: xRemoteDesktopAdmin
    state: present

- name: Enable Remote Desktop
  win_dsc:
    resource_name: xRemoteDesktopAdmin
    Ensure: present
    UserAuthentication: NonSecure