---
version: '3.3'
services:
    nexus3:
        ports:
            - '8081:8081'
        container_name: nexus
        volumes:
            - /data/nexus-data:/nexus-data
        image: sonatype/nexus3