---

- name: Create persistent storage
  file:
    path: /data/nexus-data
    state: directory
    owner: 200

- name: Create Nexus Docker Volume
  docker_volume:
    name: nexus_data

- name: Start Nexus Docker
  docker_container:
    name: nexus_repo
    image: sonatype/nexus3
    state: started
    volumes:
      - nexus_data:/nexus-data
    ports:
        - '8081:8081'