---

- name: Create persistent storage
  file:
    path: /data/nexus-data
    state: directory
    owner: 200

- name: Save docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /data/nexus-data/docker-compose.yml