---
## Connect to local repo
- name: Set up local repository
  block: 
    - name: Create folder for old repo files
      file:
        path: /etc/yum.repos.d/old_repos
        state: directory

    - name: Move old repo files
      shell: mv /etc/yum.repos.d/C*.repo /etc/yum.repos.d/old_repos/ -f
      ignore_errors: yes

    - name: Configure local CentOS Repo
      template:
        src: local.repo.j2
        dest: /etc/yum.repos.d/local.repo

  when: set_local_repo|default(true)|bool

## NTP Server
- name: Set NTP Server
  block:
    - name: Ensure chrony is installed
      package:
        name: chrony
        state: present

    - name: Copy across enterprise chrony configuration
      template:
        src: "chrony.conf.j2"
        dest: "/etc/chrony.conf"
        owner: root
        group: root
        mode: '0644'

    - name: Restart the chrony service
      service:
        name: chronyd
        state: restarted
        enabled: yes

  when: set_ntp_server|default(true)|bool

## SSH Config
- name: SSH Config
  block:
    - name: Change SSHD config
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{item.line}}"
        state: present
        validate: "sshd -t -f %s"
      with_items:
      # Don't allow root login
      - regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
      # Don't allow login for accounts without a password
      - regexp: "^PermitEmptyPasswords"
        line: "PermitEmptyPasswords no"
      notify: Restart sshd

  when: set_sshd_config|default(true)|bool

## Set up default firewall rules
- name: Set up default firewall rules
  block:
    - name: Install firewalld
      package:
        name: firewalld
        state: latest
    
    - name: Configure ports in firewall
      firewalld:
        state: "{{item.state}}"
        port: "{{item.port}}"
        zone: external
        immediate: yes
        permanent: yes
      with_items:
        - { state: 'enabled', port: 22/tcp } # SSH
        - { state: 'enabled', port: 123/udp } # NTP
    
    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes
        
  when: set_firewall_confing|default(true)|bool