---
- name: Ensure chrony is installed
  package:
    name: chrony
    state: latest
  become: yes
  become_method: sudo

- name: Copy across enterprise chrony configuration
  template:
    src: "chrony.conf.j2"
    dest: "/etc/chrony.conf"
    owner: root
    group: root
    mode: '0644'

- name: Restart the chrony service
  service:
    name: chronyd
    state: restarted
    enabled: yes

## Connect to local repo

- name: Create folder for old repo files
  file:
    path: /etc/yum.repos.d/old_repos
    state: directory

- name: Move old repo files
  shell: mv /etc/yum.repos.d/C*.repo /etc/yum.repos.d/old_repos/ -f
  ignore_errors: yes

- name: Configure local CentOS Repo
  template:
    src: local.repo.j2
    dest: /etc/yum.repos.d/local.repo

# - name: Install packages required for domain joining
#   yum:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     "{{ domain_packages }}"

# - name: Install pexpect using pip
#   pip:
#     name: pexpect

# - name: discover realml
#   shell: /bin/bash -c "/usr/sbin/realm discover {{ realm_domain }}"

# - name: Join the active directory domain
#   expect:
#     command: /bin/bash -c "/usr/sbin/realm join {{ realm_domain }} --computer-ou={{ realm_ou }} --user={{ realm_join_user }}"
#     responses:
#       Password for *: "{{ realm_join_password }}"