---
- name: Ensure chrony is installed
  package:
    name: chrony
    state: latest
  become: yes
  become_method: sudo

- name: Copy across enterprise chrony configuration
  template:
    src: "{{ ntp_config_file }}.j2"
    dest: "/etc/{{ npt_config_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Restart the chrony service
  service:
    name: chronyd
    state: restarted
    enabled: yes

- name: Join AD
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ domain_packages }}"

- name: Install pexpect using pip
  pip:
    name: pexpect

- name: discover realml
  shell: /bin/bash -c "/usr/sbin/realm discover {{ realm_domain }}"

- name: Join the active directory domain
  expect:
    command: /bin/bash -c "/usr/sbin/realm join {{ realm_domain }} --computer-ou={{ realm_ou }} --user={{ realm_join_user }}"
    responses:
      Password for *: "{{ realm_join_password }}"