---
- name: Ensure chrony is installed
  package:
    name: chrony
    state: present

- name: Copy across enterprise chrony configuration
  template:
    src: "chrony.conf.j2"
    dest: "/etc/chrony.conf"
    owner: root
    group: root
    mode: '0644'

- name: Restart the chrony service
  service:
    name: chronyd
    state: restarted
    enabled: yes

## Add IPs to host file
- name: Add IPs to host file
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item.name }}$"
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  with_items: "{{ hosts }}"

## Connect to local repo

- name: Create folder for old repo files
  file:
    path: /etc/yum.repos.d/old_repos
    state: directory

- name: Move old repo files
  shell: mv /etc/yum.repos.d/C*.repo /etc/yum.repos.d/old_repos/ -f
  ignore_errors: yes

- name: Configure local CentOS Repo
  template:
    src: local.repo.j2
    dest: /etc/yum.repos.d/local.repo
