---  
- name: Install realmd packages
  yum:
    name: sssd,adcli,samba-common-tools,oddjob,oddjob-mkhomedir,realmd
    state: present

- name: Check if machine is bound
  shell: /bin/bash -c "realm list | grep sssd"
  register: realmd_bound
  changed_when: false
  ignore_errors: true

- name: Join the domain
  shell: echo '{{ realm_join_password }}' | realm join --computer-ou="ou=Linux,ou=Servers,dc=mylab,dc=local" --user={{ realm_join_user }} {{ realm_domain }}
  register: command_result
  ignore_errors: True
  notify:
    - Restart sssd

- name: Fail the play when the realm join fails
  fail: 
    msg: "Realm join failed with this error: {{ command_result.stderr }}"
  when: "'Already joined to this domain' not in command_result.stderr and command_result.rc != 0"