--- 
- name: Install realmd packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - realmd
    - oddjob
    - oddjob-mkhomedir
    - sssd
    - samba-common
    - samba-common-tools
    - adcli
    - krb5-workstation
    - openldap-clients

# - name: Fail if default hostname
#   fail: 
#     msg: "Realm join failed with this error: {{ command_result.stderr }}"
#   when: inventory_hostname = "localhost.localdomain"

- name: Add DC to hosts file
  lineinfile:
    path: /etc/hosts
    line: '{{ realm_dc_ip }} {{ realm_dc_name }}'

- name: Checking to see if system is already joined to AD
  command: /bin/bash -c "/usr/sbin/realm list"
  register: realm_list_results
  tags: [ 'AD' ]

- name: Join domain if necessary
  block:
    - name: Join the domain
      shell: echo '{{ realm_join_password }}' | realm join --user={{ realm_join_user }} {{ realm_dc_name }} --computer-ou="ou=Linux,ou=Servers,dc=mylab,dc=local"
      register: command_result
      notify:
        - Restart sssd

    - name: Fail the play when the realm join fails
      fail: 
        msg: "Realm join failed with this error: {{ command_result.stderr }}"
      when: "'Already joined to this domain' not in command_result.stderr and command_result.rc != 0"
  
  when: ad_status.rc != 0

- name: Don't require users to provide fully qualified names
  lineinfile: 
    path: /etc/sssd/sssd.conf 
    regexp: '^(.*)use_fully_qualified_names = True(.*)$' 
    line: 'use_fully_qualified_names = False'
    backrefs: yes
  notify:
    - Restart sssd

- name: Allow the Sudoers AD group to logon to the system
  command: /bin/bash -c "/usr/sbin/realm permit -g {{realm_sudoers_group}}"