---

- name: Enable CentOS8 PowerTools repo
  # NB: doesn't run command  `dnf config-manager --set-enabled PowerTools` as can't make that idempotent
  lineinfile: 
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    create: false # so raise error if not already installed
    regexp: enabled=
    line: enabled=1
  when: ansible_distribution_major_version == "8"


  
- name: Start icinga2 service
  service:
    name: icinga2
    state: started
    enabled: yes